### ISSUE TITLE
very neat cheat

### ISSUE THREAD

**Issue by Jayderp** [mikeboydvideo/MikeBoydGame#7]
had to convert it to a gif thanks to github
![ezgif-4-5abac63ab8af](https://user-images.githubusercontent.com/49515406/66491650-964a4f80-eb0f-11e9-819e-4986fafcffc2.gif)

**Comment by proprr** [comment]
This is an open source game so you can’t really fix it.

**Comment by Jayderp** [comment]
@proprr I agree. Closed.
